In [1]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('CHART1_NJ.csv')

# Display basic information about the dataset
print("Dataset shape:", df.shape)
print("\nFirst few rows:")
print(df.head())
print("\nColumn names:", df.columns.tolist())
print("\nBasic statistics:")
print(df.describe())

Dataset shape: (12190, 18)

First few rows:
                  Clean Plaintiff Plaintiff Type   1996   1997   1998   1999  \
0                           Other          Other  65388  62181  59402  53654
1            Encore Capital Group     Debt Buyer      7     21     11     36
2                     Capital One     Major Bank      3      6      2     52
3  New Century Financial Services     Debt Buyer     77    331   5613   3090
4     Sherman Financial Group LLC     Debt Buyer      6     57     75     28

    2000   2001   2002   2003   2004   2005   2006   2007   2008   2009  \
0  54680  53571  53761  53221  50714  45480  48067  50101  52247  48197
1    176    700    982    901   3691   5318  13143  14147  28204  21049
2   1287   7732  18217  24090  15341  15129  19733  31198  38481  41299
3   8616  29323  17288  51698  22700  25259  18798  18761  33816  35061
4     13     37    103   1583   1970   2284   4269  10807  10072   6214

    2010   2011
0  44847  41119
1  36870  40926
2  37936  26314
3  20502  22327
4  11692  10644

Column names: ['Clean Plaintiff', 'Plaintiff Type', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011']

Basic statistics:
               1996          1997          1998          1999          2000  \
count  12190.000000  12190.000000  12190.000000  12190.000000  12190.000000
mean       9.663331     10.272108     10.595324      9.195898      9.714192
std      595.980490    571.238255    551.025139    491.516100    505.487293
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000      0.000000      0.000000
max    65388.000000  62181.000000  59402.000000  53654.000000  54680.000000

               2001          2002          2003          2004          2005  \
count  12190.000000  12190.000000  12190.000000  12190.000000  12190.000000
mean      11.496226     12.409024     16.583265     14.459311     15.064151
std      560.476325    542.873671    714.079735    541.754114    526.764287
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000      0.000000      0.000000
max    53571.000000  53761.000000  53221.000000  50714.000000  45480.000000

               2006          2007          2008          2009          2010  \
count  12190.000000  12190.000000  12190.000000  12190.000000  12190.000000
mean      16.723380     20.459229     23.490074     22.629532     22.908696
std      572.715402    669.138444    747.251151    714.061452    702.176908
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      0.000000
75%        0.000000      0.000000      0.000000      0.000000      0.000000
max    48067.000000  50101.000000  52247.000000  48197.000000  44847.000000

               2011
count  12190.000000
mean      19.103692
std      635.491179
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max    41119.000000